services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - author=wittiden
      - project=TaskService
      - version=2.0.0
    image: task_service_app:1.0.0
    container_name: task_service_app
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - network
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 8000)); s.close()"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          target: .
          path: /app
        - action: rebuild
          path: requirements-prod.txt

  db:
    image: postgres:16-alpine
    container_name: task_service_db
    restart: unless-stopped
    networks:
      - network
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - db_volume:/var/lib/postgresql/data
    stop_grace_period: 30s
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0-alpine
    container_name: task_service_redis
    restart: unless-stopped
    stop_grace_period: 30s
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    networks:
      - network
    volumes:
      - redis_volume:/data
    environment:
      - REDIS_PASS=${REDIS_PASS}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASS} ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    container_name: task_service_rabbitmq
    networks:
      - network
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    container_name: task_service_celery
    command: celery -A app.common.task_service.utils worker --loglevel=info --concurrency=2
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER:-user}:${RABBITMQ_PASSWORD:-password}@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASS}@redis:6379/0
    volumes:
      - .:/app
    stop_grace_period: 30s
    depends_on:
      rabbitmq:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4:9.0.0
    container_name: task_service_pgadmin
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - network
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    profiles:
      - pgadmin

  redisinsight:
    image: redislabs/redisinsight:3.8.0
    container_name: task_service_redisinsight
    volumes:
      - redisinsight_volume:/data
    ports:
      - "5540:5540"
    restart: unless-stopped
    networks:
      - network
    stop_grace_period: 30s
    profiles:
      - redisinsight

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: task_service_prometheus
    stop_grace_period: 30s
    networks:
      - network
    expose:
      - "9090"
    volumes:
      - ./app/common/observability/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.1-slim
    container_name: task_service_grafana
    stop_grace_period: 30s
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - network
    volumes:
      - grafana_volume:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    profiles:
      - grafana

  loki:
    image: grafana/loki:3.7.0
    container_name: task_service_loki
    stop_grace_period: 30s
    networks:
      - network
    expose:
      - "3100"
    volumes:
      - ./app/common/observability/logs/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_volume:/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.6.0
    container_name: task_service_promtail
    networks:
      - network
    volumes:
      - ./app/common/observability/logs/promtail-config.yaml:/etc/promtail/local-config.yaml
      - ./logs:/var/log/app:ro
    command:
      - -config.file=/etc/promtail/local-config.yaml
    stop_grace_period: 30s
    restart: unless-stopped
    expose:
      - "9080"



volumes:
  db_volume:
    name: task_service_db_volume
  pgadmin_volume:
    name: task_service_pgadmin_volume
  redis_volume:
    name: task_service_redis_volume
  redisinsight_volume:
    name: task_service_redisinsight_volume
  prometheus_volume:
    name: task_service_prometheus_volume
  grafana_volume:
    name: task_service_grafana_volume
  loki_volume:
    name: task_service_loki_volume
  rabbitmq_volume:
    name: task_service_rabbitmq_volume


networks:
  network:
    driver: bridge
    name: task_service_network
