"""create_indexes

Revision ID: 0769b1ef7183
Revises: 71794fe47914
Create Date: 2026-07-09 18:54:24.976471

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0769b1ef7183'
down_revision: Union[str, Sequence[str], None] = '71794fe47914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_audience'), 'refresh_tokens', ['audience'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expired_at'), 'refresh_tokens', ['expired_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_issued_at'), 'refresh_tokens', ['issued_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_audits_changed_at'), 'user_audits', ['changed_at'], unique=False)
    op.create_index(op.f('ix_user_audits_field_name'), 'user_audits', ['field_name'], unique=False)
    op.create_index(op.f('ix_user_audits_user_id'), 'user_audits', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_closed_at'), 'users', ['closed_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_closed_at'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_audits_user_id'), table_name='user_audits')
    op.drop_index(op.f('ix_user_audits_field_name'), table_name='user_audits')
    op.drop_index(op.f('ix_user_audits_changed_at'), table_name='user_audits')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_issued_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expired_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_audience'), table_name='refresh_tokens')
    # ### end Alembic commands ###
