"""create_task_models

Revision ID: ca7cd3687b65
Revises: 0769b1ef7183
Create Date: 2026-07-11 16:37:42.900966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca7cd3687b65'
down_revision: Union[str, Sequence[str], None] = '0769b1ef7183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('important_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'TRIVIAL', name='task_important_level_enum'), nullable=False),
    sa.Column('schedule_type', sa.Enum('URGENT', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'POSTPONED', 'BACKLOG', name='task_schedule_enum'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_closed_at'), 'tasks', ['closed_at'], unique=False)
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_important_level'), 'tasks', ['important_level'], unique=False)
    op.create_index(op.f('ix_tasks_schedule_type'), 'tasks', ['schedule_type'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('task_audits',
    sa.Column('task_audit_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('task_audit_id')
    )
    op.create_index(op.f('ix_task_audits_changed_at'), 'task_audits', ['changed_at'], unique=False)
    op.create_index(op.f('ix_task_audits_field_name'), 'task_audits', ['field_name'], unique=False)
    op.create_index(op.f('ix_task_audits_new_value'), 'task_audits', ['new_value'], unique=False)
    op.create_index(op.f('ix_task_audits_old_value'), 'task_audits', ['old_value'], unique=False)
    op.create_index(op.f('ix_task_audits_task_id'), 'task_audits', ['task_id'], unique=False)
    op.alter_column('user_audits', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_audits', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_audits_new_value'), 'user_audits', ['new_value'], unique=False)
    op.create_index(op.f('ix_user_audits_old_value'), 'user_audits', ['old_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_audits_old_value'), table_name='user_audits')
    op.drop_index(op.f('ix_user_audits_new_value'), table_name='user_audits')
    op.alter_column('user_audits', 'old_value',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_audits', 'new_value',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_task_audits_task_id'), table_name='task_audits')
    op.drop_index(op.f('ix_task_audits_old_value'), table_name='task_audits')
    op.drop_index(op.f('ix_task_audits_new_value'), table_name='task_audits')
    op.drop_index(op.f('ix_task_audits_field_name'), table_name='task_audits')
    op.drop_index(op.f('ix_task_audits_changed_at'), table_name='task_audits')
    op.drop_table('task_audits')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_schedule_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_important_level'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_closed_at'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
