"""hotfix_audits

Revision ID: 0926bfac7672
Revises: ca7cd3687b65
Create Date: 2026-07-12 13:53:27.756377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0926bfac7672'
down_revision: Union[str, Sequence[str], None] = 'ca7cd3687b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_audits', 'new_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user_audits', sa.Column('user_audit_id', sa.Uuid(), nullable=False))
    op.alter_column('user_audits', 'new_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_audits', 'user_audits_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_audits', sa.Column('user_audits_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('user_audits', 'new_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_audits', 'user_audit_id')
    op.alter_column('task_audits', 'new_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
